### ISSUE TITLE
When I run train.py, I got an import Error

### ISSUE THREAD

**Issue by Hydraz320** [MarvinTeichmann/KittiSeg#28]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import commentjson
  File "C:\Users\hydraz320\Anaconda3\lib\site-packages\commentjson\__init__.py", line 1, in <module>
    from commentjson import dump
ImportError: cannot import name 'dump'

May I ask that which os you were using?  Thanks a lot.

**Comment by MarvinTeichmann** [comment]
This seams to be an issue with your commentjson version. I am using Vesion `commentjson==0.6`. 

A work around would be to replace `from commentjson import dump` with `from json import dump`. You can't use comments in the config file then. However KittiSeg currently does not have any comments in it, so it will work out of the box.

**Comment by WPSanberg** [comment]
Hi, I am using commentjson 0.6 as well, but I get the same error. It might be windows (although I'm on Debian 4.9.13-1) and/or python>3.4 related, see [https://github.com/vaidik/commentjson/issues/3](url). 

I have used your workaround and it does not complain anymore, but it might have led to a different problem. I'll submit a separate issue for that in case it's unrelated.

**Comment by lemhell** [comment]
@WPSanberg 
Hello, I've been getting the same error, then it was suggested in the [Issue 8](https://github.com/MarvinTeichmann/KittiSeg/issues/8) to use Python 2.7, I installed everything for 2.7 and the issue was resolved for me.

**Comment by Hydraz320** [comment]
Well, I use python2.7 and ubuntu16.04 and get the expected results.

**Comment by MarvinTeichmann** [comment]
ok. This issue seams to be fixed. So I close it for now.

Regarding commentjson: I properly should look for an alternative if it does not work with python 3.4. In practise this is a minor think. In theory json could be used and/or any wrapper which removes comments.
